version: "3.3"
services:
  db-tests:
    container_name: db-tests
    build:
      context: .
      dockerfile: ./tests/Dockerfile-db-test
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=lsg11
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432

  # spring-service-1 and spring-service-2 are used to illustrate scenarios with a fixed number of servers
  # with static and well know names.
  spring-service-1:
    container_name: spring-service-1
    hostname: spring-service-1
    build:
      context: .
      dockerfile: ./tests/Dockerfile-spring
    environment:
      SERVER_PORT: 8083
      DB_URL: "jdbc:postgresql://db-tests:5432/postgres?user=postgres&password=lsg11"
    ports:
      - 8083:8083
    depends_on:
      - db-tests

  spring-service-2:
    container_name: spring-service-2
    hostname: spring-service-2
    build:
      context: .
      dockerfile: ./tests/Dockerfile-spring
    environment:
      SERVER_PORT: 8082
      DB_URL: "jdbc:postgresql://db-tests:5432/postgres?user=postgres&password=lsg11"
    ports:
      - 8082:8082
    depends_on:
      - db-tests

  # spring-service is used to illustrate scenario with a dynamic number of servers
  # without static and well know names.
  # We will use docker compose scaling to create multiple instances of this service
  spring-service:
    build:
      context: .
      dockerfile: ./tests/Dockerfile-spring
    environment:
      SERVER_PORT: 8080
      DB_URL: "jdbc:postgresql://db-tests:5432/postgres?user=postgres&password=lsg11"
    depends_on:
      - db-tests

  # The service running the load-balancer
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./tests/Dockerfile-nginx
    ports:
      - 8080:8080
    volumes:
      - ./tests/nginx:/etc/nginx
    depends_on:
      - spring-service-1
      - spring-service-2